geoDjango/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.static import static
from geoDjango import settings

from django.contrib import admin
import gestionR

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'users.views.login', name='index'),
    url(r'^Home$', 'gestionR.views.index', name='index'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^test/', include(include('gestionR.urls'))),
    url(r'^android/', include(include('android_root.urls'))),
    url(r'^Enquetes$','gestionR.views.enquetes'),
    url(r'^FormEnquete$','gestionR.views.formEnquete'),
    url(r'^NextFormEnquete/(\d+)/$','gestionR.views.formEnqueteNext'),
    url(r'^PresenceInstutionnelle/(\d+)/$','gestionR.views.presenceinstitutionnelle'),
    url(r'^Plan/(\d+)/$','gestionR.views.plansCommunauxForm'),
    url(r'^Materiels/(\d+)/$','gestionR.views.materiels'),
    url(r'^Equipements/(\d+)/$','gestionR.views.equipements'),
    url(r'^MoyenCommunications/(\d+)/$','gestionR.views.communications'),
    url(r'^Transports/(\d+)/$','gestionR.views.tranports'),
    url(r'^RessourcesHumaines/(\d+)/$','gestionR.views.ressourceshumaines'),
    url(r'^RessourcesDIntervention/(\d+)/$','gestionR.views.interventions'),
    url(r'^Evaluation/(\d+)/$','gestionR.views.evaluations'),
    url(r'^EvaluationRisque/(\d+)/$','gestionR.views.evaluationsrisque'),
    url(r'^Sections$','gestionR.views.sections'),
    url(r'^logout$','users.views.logout'),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('users.views',
    # Examples:
    # url(r'^$', 'buildchange.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'add','addUser'),

)

gestionR/forms.py
#!/usr/bin/env python
#-*- coding: utf-8 -*-
from django import forms
from gestionR.models import *
from django.forms.widgets import DateInput, SelectMultiple, CheckboxSelectMultiple, Select, RadioSelect, FileInput
from gestionR.Data import *
#
# __author__ = 'Suy'

class EnqueteForm(forms.ModelForm):
    class Meta:
        model = Enquete
        exclude = ['datecreation','datemodification','user']
        widgets = {
            'debutenquete': DateInput(attrs={'type': 'date'}),
            'finenquete': DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(EnqueteForm, self).__init__(*args, **kwargs)
        self.fields['finenquete'].required = False




class FormFileWord(forms.ModelForm):
    class Meta:
        model = FileWord
        exclude = ['enquete']
        widgets = {
            # 'file': FileInput(attrs={'type':'file','class':"btn btn-default", 'style':"float: right"}),
        }

class PerceptionForm(forms.ModelForm):
    risque = forms.CharField(widget=CheckboxSelectMultiple(choices=RISQUE))
    risqueseg = forms.CharField(widget=CheckboxSelectMultiple(choices=EFFETSEG))
    priorite1 = forms.CharField(widget=Select(choices=RISQUE))
    priorite2 = forms.CharField(widget=Select(choices=RISQUE))
    priorite3 = forms.CharField(widget=Select(choices=RISQUE))
    priorite4 = forms.CharField(widget=Select(choices=RISQUE))
    class Meta:
        model = Perception
        exclude = ['enquete','risques','local','risqueseg']
        widget = {
        }


class DegreDexpositionForm(forms.Form):
    choix = []

    # class Meta:
    #     model = DegreDexposition
    #     exclude = ['local','risque']
    # choix = [
    #     (c.id,c)for c in HtiAdm3.objects.all()
    # ]
    # localsd1 = forms.CharField(widget=SelectMultiple(choices=choix,attrs={'class':'chosen', 'style':'width:500px;'}))
    # localsd2 = forms.CharField(widget=SelectMultiple(choices=choix,attrs={'class':'chosen', 'style':'width:500px;'}))
    # localsd3 = forms.CharField(widget=SelectMultiple(choices=choix,attrs={'class':'chosen', 'style':'width:500px;'}))
    def __init__(self, *args, **kwargs):
        commune  = kwargs.pop('commune')
        super(DegreDexpositionForm, self).__init__(*args, **kwargs)
        choix = [
            (c.id,c)for c in HtiAdm3.objects.filter(id_2=commune.id)
        ]
        self.fields['localsd1'] = forms.CharField(widget=SelectMultiple(choices=choix,attrs={'class':'chosen', 'style':'width:500px;'}))
        self.fields['localsd2'] = forms.CharField(widget=SelectMultiple(choices=choix,attrs={'class':'chosen', 'style':'width:480px;'}))
        self.fields['localsd3'] = forms.CharField(widget=SelectMultiple(choices=choix,attrs={'class':'chosen', 'style':'width:500px;'}))
        self.fields['localsd1'].label = 'Fortement'
        self.fields['localsd2'].label = 'Modérément'
        self.fields['localsd3'].label = 'Faiblement'



class VulnerabiliteForm(forms.Form):
    choix = []

    # class Meta:
    #     model = DegreDexposition
    #     exclude = ['local','risque']

    def __init__(self, *args, **kwargs):
        commune  = kwargs.pop('commune')
        super(VulnerabiliteForm, self).__init__(*args, **kwargs)
        choix = [
            (c.id,c)for c in HtiAdm3.objects.filter(id_2=commune.id)
        ]
        self.fields['localsd1'] = forms.CharField(widget=SelectMultiple(choices=choix,attrs={'class':'chosen', 'style':'width:500px;'}))
        self.fields['localsd2'] = forms.CharField(widget=SelectMultiple(choices=choix,attrs={'class':'chosen', 'style':'width:500px;'}))
        self.fields['localsd3'] = forms.CharField(widget=SelectMultiple(choices=choix,attrs={'class':'chosen', 'style':'width:500px;'}))
        self.fields['localsd1'].label = 'Fort'
        self.fields['localsd2'].label = 'Modéré'
        self.fields['localsd3'].label = 'Faible'



        # # class CommuneForm(ModelForm):
# #     class Meta:
# #         model = HaitiAdm3Stats
#
# class EnqueteForm(forms.Form):
#     choix = []
#     debutenquete = forms.DateTimeField(label="Début de l'enquête :",widget=DateInput(attrs={'type': 'date','class':'form-control'}))
#     finenquete = forms.DateTimeField(label="Fin de l'enquête :",widget=DateInput(attrs={'type': 'date','class':'form-control'}))
#     risque = forms.CharField(widget=SelectMultiple(choices=RISQUE))
#     risqueR = forms.CharField(widget=SelectMultiple(choices=()))
#     risqueseq = forms.CharField(widget=CheckboxSelectMultiple(choices=EFFETSEG))
#     priorite1 = forms.CharField(label="Risque prioritaire #1 :", widget=Select(choices=()))
#     priorite2 = forms.CharField(label="Risque prioritaire #2 :", widget=Select(choices=()))
#     priorite3 = forms.CharField(label="Risque prioritaire #3 :", widget=Select(choices=()))
#     priorite4 = forms.CharField(label="Risque prioritaire #4 :", widget=Select(choices=()))
#     degre = forms.CharField(label="degre d'exposition :",widget=Select(choices=DEGRE))
#     niveau = forms.CharField(label="Niveau :",widget=Select(choices=DEGRE))
#     section = forms.CharField(label="Sections Communales :")
#
#     def __init__(self, commune,*args, **kwargs):
#         super(EnqueteForm, self).__init__(*args, **kwargs)
#         self.commune = commune
#         l = HaitiAdm3Stats.objects.filter(commune=self.commune)
#         for s in l:
#             self.choix.append((s.id,s.section))
#
#         self.fields['section'].widget=Select(choices=self.choix)
#
#
#     def getCommune(self):
#         return self.commune
#
#
class PresenceInstitutForm(forms.ModelForm):

    class Meta:
        model = PresenceInstitutionnelle
        exclude = ['enquete']
        widgets = {
            'existenceclpc':RadioSelect(),
        }
    def __init__(self, *args, **kwargs):
        commune  = kwargs.pop('commune')
        super(PresenceInstitutForm, self).__init__(*args, **kwargs)
        self.fields['local'].queryset = HtiAdm3.objects.filter(id_2=commune.id)

#
class PlansCommunauxForm(forms.ModelForm):
    class Meta:
        model = PlansCommunaux
        exclude = ['enquete']

#
class MateriellesForm(forms.ModelForm):
    class Meta:
        model = Materielles
        exclude = ['enquete']
#
#
class EquipementForm (forms.ModelForm):
    class Meta:
        model = Equipement
        exclude = ['enquete']
#
#
class MoyenDeCommunicationForm(forms.ModelForm):
    class Meta:
        model = MoyenDeCommunication
        exclude = ['enquete']
#
#
#
#
class MoyenDeTransportForm(forms.ModelForm):
    class Meta:
        model = MoyenDeTransport
        exclude = ['enquete']



class RessourceHumaineForm(forms.ModelForm):
    class Meta:
        model = RessourceHumaine
        exclude = ['enquete']

class RessourceDInterventionForm(forms.ModelForm):
    class Meta:
        model = RessourceDIntervention
        exclude = ['enquete']


class EvaluationForm(forms.ModelForm):
    class Meta:
        model = Evaluation
        exclude = ['enquete']

geoDjango/templates/enquete/form.html
{% extends 'masterpage.html' %}
{% load staticfiles %}
{% block content %}
    <div id="page-wrapper">

        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-money"></i>&nbsp;Perception de l'exposition aux ménaces</h3>
              </div>
        <div class="row">
            <form name="Example" action="/FormEnquete" role="form" method="post">
                {% csrf_token %}
               <table id="form1">
                   <tr>
                       <td colspan="3">
               <div class="error">{{ form.errors }}{{ formp.errors }}</div>
                        </td>
                   </tr>
                   <tr>
              <div class="form-group">
                  <td>
                {{ form.local.label_tag }}
                      </td>
                  <td>
                {{ form.local }}
                      </td>
                  <td>
                <p class="help-block">{{ form.debutenquete.error_messages }}</p>
                  </td>
              </div>
                </tr>
                 <tr>
              <div class="form-group">
                  <td>
                {{ form.debutenquete.label_tag }}
                  </td>
                     <td>
                {{ form.debutenquete }}
                         </td>
                  <td>
                <p class="help-block">{{ form.debutenquete.error_messages }}</p>
                   </td>
              </div>
                </tr>
                   <tr>
              <div class="form-group">

                  <td>
                {{ form.finenquete.label_tag }}
                      </td>
                  <td>
                {{ form.finenquete }}
                      </td>
                  <td>
                <p class="help-block">{{ form.finenquete.error_messages }}</p>
                  </td>
              </div>

               </tr>
              <div class="form-group">
                <tr>
                    <td colspan="3">
                        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-money"></i>&nbsp;1. Risques</h3>
                    </div>
                </div>
              </div>
                  </div>
                    </td>
                  </tr>
                  <tr>
                <div class="">
                    <td colspan="3">
                  {{ formp.risque }}
                        </td>

                </div>
                  </tr>

              </div>

              <div class="form-group">
                  <tr>
                  <td  colspan="3">
                      <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-money"></i>&nbsp;2. Risques Secondaires</h3>
                    </div>
                </div>
              </div>
                  </div>
                   </td>
                  </tr>
                   <tr>
                  <td colspan="3" style="padding-left:30px;">
                  {% for inp in formp.risqueseg %}
                    {{ inp }}<br/>
                  {% endfor %}
                  </td>
                  </tr>
              </div>

              <div class="form-group">
                  <tr>
                   <td colspan="3">
                       <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-money"></i>&nbsp;3. Priorisation des risques</h3>
                    </div>
                </div>
              </div>
                  </div>
                      </td>
                      </tr>
                  <tr>
                      <td style="padding-left:30px;">
                    {{ formp.priorite1.label_tag }}</td><td colspan="2">&emsp;{{ formp.priorite1 }}
                      </td>
                   </tr>
                  <tr><td style="padding-left:30px;">
                    {{ formp.priorite2.label_tag }}</td><td colspan="2">&emsp;{{ formp.priorite2 }}
                    </td></tr>
                  <tr><td style="padding-left:30px;">
                    {{ formp.priorite3.label_tag }}</td><td colspan="2">&emsp;{{ formp.priorite3 }}
                    </td></tr>
                  <tr><td style="padding-left:30px;">
                    {{ formp.priorite4.label_tag }}</td><td colspan="2">&emsp;{{ formp.priorite4 }}
                  </td>
                  </tr>
              </div>
                   </tr>

            <tr>
                <td> </td>
                <td >
                    <button type="submit" class="btn btn-default">Next --></button>
                </td>
                <td style="width:20%"></td>
               </tr>
           </table>
            </form>

        </div><!-- /.row -->
       </div>
              </div>
            </div>
      </div><!-- /#page-wrapper -->

{% endblock %}

geoDjango/templates/enquete/form1.html
{% extends 'masterpage.html' %}
{% load staticfiles %}
{% block content %}
    <div id="page-wrapper">

        <div class="row">
          <div class="col-lg-12">
            <h1 style="color: #00008B">Perception de l'exposition aux ménaces</h1>


          </div>
        </div><!-- /.row -->

        <div class="row">
          <div class="col-lg-6">

            <form role="form">

              <div class="form-group">
                {{ form.debutenquete.label_tag }}
                {{ form.debutenquete }}
                <p class="help-block">{{ form.debutenquete.error_messages }}</p>
              </div>

              <div class="form-group">
                {{ form.finenquete.label_tag }}
                {{ form.finenquete }}
                <p class="help-block">{{ form.finenquete.error_messages }}</p>
              </div>

              <div class="form-group">
                <label>Risques</label>
                <div class="">
                  {{ form.risque }}
                    <span  style="background: url({% static 'image/arrow-right.png' %}) center right no-repeat;width: 200px;height: 30px;">
                        <a href="#" id="sendtoright" onclick="sendtoright();">&nbsp;</a>
                    </span>
                    <span style="background: url({% static 'image/arrow-left.png' %}) center left no-repeat;width: 200px;height: 30px;">
                       <a href="#" id="sendtoright">&nbsp;</a>
                    </span>
                  {{ form.risqueR }}

	                <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
                  <script type="text/javascript">
                    $(document).ready(function(){
                        $(document).on("click",'#sendtoright',function() {
                    // alert("hello ");


                var selectVal = $('#id_risque :selected').val();

                new Option('Foo', 'foo', true, true)
                $('#id_risqueR').append("<option >"+selectVal+"</option>");
                $('#id_priorite1').append("<option >"+selectVal+"</option>");
                $('#id_priorite2').append("<option >"+selectVal+"</option>");
                $('#id_priorite3').append("<option >"+selectVal+"</option>");
                $('#id_priorite4').append("<option >"+selectVal+"</option>");
                //alert(selectVal);

                });
                 });

                /*<script type="text/javascript" src="{% static 'jscript/perceptionform.js' %}">*/
                </script>
                </div>
                <script type="text/javascript" src="{% static 'jscript/perceptionform.js' %}"></script>

              </div>

              <div class="form-group">
                <h4 style="color: #008800;">2. Risques Secondaires</h4>
                  {% for inp in form.risqueseq %}
                    {{ inp }}<br/>
                  {% endfor %}
              </div>

              <div class="form-group">
                <h4 style="color: #008800;">3. Priorisation des risques</h4>
                    {{ form.priorite1.label_tag }}&emsp;{{ form.priorite1 }}<br/>
                    {{ form.priorite2.label_tag }}&emsp;{{ form.priorite2 }}<br/>
                    {{ form.priorite3.label_tag }}&emsp;{{ form.priorite3 }}<br/>
                    {{ form.priorite4.label_tag }}&emsp;{{ form.priorite4 }}<br/>
              </div>

               <div class="form-group">
                <h4 style="color: #008800;">4. Section communales / Localités exposés et degré d'exposition</h4>
                  <h5 style="color: #008800;">4. Quelles communes / section communales sont les plus exposees aux risques prioritaire identifiees ?</h5>

                    {{ form.priorite1.label_tag }}&emsp;{{ form.priorite1 }}<br/>
                    {{ form.priorite2.label_tag }}&emsp;{{ form.priorite2 }}<br/>
                    {{ form.priorite3.label_tag }}&emsp;{{ form.priorite3 }}<br/>
                    {{ form.priorite4.label_tag }}&emsp;{{ form.priorite4 }}<br/>
                    {{ form.degre.label_tag }}&emsp;{{ form.degre }}<br/>
                    {{form.setion.label_tag}}&emsp;{{form.section}}
                  {{form.setion.label_tag}}&emsp;{{form.section}}
                  {{form.setion.label_tag}}&emsp;{{form.section}}
              </div>

              <button type="submit" class="btn btn-default">Submit Button</button>
              <button type="reset" class="btn btn-default">Reset Button</button>
            </form>

          </div>

        </div><!-- /.row -->

      </div><!-- /#page-wrapper -->

{% endblock %}

geoDjango/templates/enquete/list.html
{% extends 'masterpage.html' %}
{% block content %}
<div id="page-wrapper">



{#        <a href="/FormEnquete" class="btn btn-default"  style="margin-left: 10px;float: right">Créer nouveau enquete</a>#}
        <div class="row" style="border: none">
          <div class="col-lg-12" style="border: none">
            <div class="panel panel-primary" style="border: none">

                <form id="form1file" action="/Enquetes?u=1" onchange="document.getElementById('form1file').submit()" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="panel-body"  style="float: right;width: 700px;">
                        <a href="/FormEnquete" class="btn btn-default"  style="margin-left: 10px;float: right">Créer nouveau enquete</a>{{ formfile }}

                    </div>
                </form>
            </div>
          </div>
        </div><!-- /.row -->
        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-money"></i> Enquetes communales</h3>
              </div>
              <div class="panel-body">
                <div class="table-responsive">

                  <table class="table table-bordered table-hover table-striped tablesorter">
                    <thead>
                      <tr>
                        <th>Action</th>
                        <th>Date d'enregistrement</th>
                         <th>Date dernière modification</th>
                        <th>Date début</th>
                        <th>Date de fin</th>
                        <th>Commune </th>
                        <th>Enqueteur </th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for enquete in enquetes %}
                        <tr>
                            <td>
                                {% if enquete.complete %}
                                {% else %}
                                    <a href="/NextFormEnquete/{{ enquete.id }}/" class="table-actions-button ic-table-edit" title="Compléter enquete" style="color: red">Comléter</a>
                                {% endif %}
                                <a href="" class="table-actions-button ic-table-edit" title="Editer">Modifier</a>
                                <a href="" class="table-actions-button ic-table-delete" title="Effacer">Supprimer</a>
							</td>
                            <td>{{ enquete.datecreation }}</td>
                            <td>{{ enquete.datemodification }}</td>
                            <td>{{ enquete.debutenquete }}</td>
                            <td>{{ enquete.finenquete }}</td>
                            <td>{{ enquete.local.name_2 }}</td>
                            <td>{{ enquete.user.last_name }} {{ enquete.user.first_name }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
                <div class="text-right">
                  <a href="/test/Mapsallenquete/">View on map <i class="fa fa-arrow-circle-right"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div><!-- /.row -->

      </div><!-- /#page-wrapper -->
{% endblock %}

geoDjango/templates/enquete/nextform-copy.html
{% extends 'masterpage.html' %}
{% load staticfiles %}
{% block content %}
    <div id="page-wrapper">

        <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-money"></i>&nbsp;Perception de l'exposition aux ménaces</h3>
              </div>


        <form action="/NextFormEnquete/{{ id }}/" method="post" role="form">
            {% csrf_token %}
  <fieldset>
            <table id="form1">
        <div class="row">
          <div class="col-lg-6">
              <tr><td><span>Risque #1</span></td><td colspan="2">{{ formr1.as_p }}</td></tr>
              <tr><td colspan="3"> <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                    </div>
                </div>
              </div>
                  </div></td></tr>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
              <tr><td><span>Risque #2</span></td><td colspan="2">{{ formr2.as_p }}</td></tr>
             <tr><td colspan="3"> <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                    </div>
                </div>
              </div>
                  </div></td></tr>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
              <tr><td><span>Risque #3</span></td><td colspan="2">{{ formr3.as_p }}</td></tr>
               <tr><td colspan="3"> <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                    </div>
                </div>
              </div>
                  </div></td></tr>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
               <tr><td><span>Risque #4</span></td><td colspan="2">{{ formr4.as_p }}</td></tr>

          </div>
        </div>
                </table>
    </fieldset>

    <fieldset>

            <table id="form1">
        <div class="row">
          <div class="col-lg-6">
              <tr><td><span>Risque #1</span></td><td colspan="2">{{ formvr1.as_p }}</td></tr>
              <tr><td colspan="3"> <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                    </div>
                </div>
              </div>
                  </div></td></tr>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
              <tr><td><span>Risque #2</span></td><td colspan="2">{{ formvr2.as_p }}</td></tr>
             <tr><td colspan="3"> <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                    </div>
                </div>
              </div>
                  </div></td></tr>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
              <tr><td><span>Risque #3</span></td><td colspan="2">{{ formvr3.as_p }}</td></tr>
               <tr><td colspan="3"> <div class="row">
          <div class="col-lg-12">
            <div class="panel panel-primary">
                        <div class="panel-heading">
                    </div>
                </div>
              </div>
                  </div></td></tr>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
               <tr><td><span>Risque #4</span></td><td colspan="2">{{ formvr4.as_p }}</td></tr>

          </div>
        </div>




        <div class="row">
          <div class="col-lg-6">
              <tr><td></td><td colspan="2">
              <button type="submit" class="btn btn-default">Next --></button>
                  </td>
              </tr>

          </div>

        </div><!-- /.row -->
                </table>
    </fieldset>


        </form>

     </div>
              </div>
            </div>
      </div><!-- /#page-wrapper -->



{% endblock %}